// Internal reference data ("Dữ liệu nội bộ") — suggested SELLING tariff prices,
// sourced from "ASW LOCAL CHARGES TARIFF SUGGESTION 2026.xlsx" (Suggest columns).
// Used to: (1) populate the "Dữ liệu nội bộ" tab, and (2) warn the user inline
// when an entered selling price differs from the suggested tariff.
// Shape: TARIFF_SUGGEST[mode][itemKey] = { price: number|null, unit: string, note?: string }

export const TARIFF_SUGGEST = {
  fcl20: {
    exThc: { price: 160, unit: 'Container' },
    exDocFee: { price: 50, unit: 'Bill of Lading' },
    exContSeal: { price: 10, unit: 'Container' },
    exTelex: { price: 35, unit: 'Bill of Lading' },
    exHandling: { price: 30, unit: 'Bill of Lading' },
    exAms: { price: 45, unit: 'Bill of Lading' },
    exEbs: { price: null, unit: 'Container', note: 'At cost as per carrier tariff' },
    exVgm: { price: 10, unit: 'Shipment' },
    exAmend: { price: 45, unit: 'Bill of Lading' },
    exSwitch: { price: 45, unit: 'Bill of Lading' },
    exLateSi: { price: 45, unit: 'Bill of Lading' },
    exAmsAmend: { price: 60, unit: 'Bill of Lading' },
    exIsf: { price: 45, unit: 'Bill of Lading' },
    imThc: { price: 150, unit: 'Container' },
    imDoFee: { price: 55, unit: 'Bill of Lading' },
    imHandling: { price: 30, unit: 'Bill of Lading' },
    imEmc: { price: 15, unit: 'Container', note: 'As per carrier tariff' },
    imCic: { price: 55, unit: 'Container', note: 'As per carrier tariff' },
    imCleaning: { price: 13, unit: 'Container', note: 'As per carrier tariff' },
  },
  fcl40: {
    exThc: { price: 250, unit: 'Container' },
    exDocFee: { price: 50, unit: 'Bill of Lading' },
    exContSeal: { price: 10, unit: 'Container' },
    exTelex: { price: 35, unit: 'Bill of Lading' },
    exHandling: { price: 30, unit: 'Bill of Lading' },
    exAms: { price: 45, unit: 'Bill of Lading' },
    exEbs: { price: null, unit: 'Container', note: 'At cost as per carrier tariff' },
    exVgm: { price: 10, unit: 'Shipment' },
    exAmend: { price: 45, unit: 'Bill of Lading' },
    exSwitch: { price: 45, unit: 'Bill of Lading' },
    exLateSi: { price: 45, unit: 'Bill of Lading' },
    exAmsAmend: { price: 60, unit: 'Bill of Lading' },
    exIsf: { price: 45, unit: 'Bill of Lading' },
    imThc: { price: 220, unit: 'Container' },
    imDoFee: { price: 55, unit: 'Bill of Lading' },
    imHandling: { price: 30, unit: 'Bill of Lading' },
    imEmc: { price: 30, unit: 'Container', note: 'As per carrier tariff' },
    imCic: { price: 200, unit: 'Container', note: 'As per carrier tariff' },
    imCleaning: { price: 26, unit: 'Container', note: 'As per carrier tariff' },
  },
  lcl: {
    exThc: { price: 11, unit: 'W/M', note: 'Minimum charge 1 CBM' },
    exDocFee: { price: 45, unit: 'Bill of Lading' },
    exCfs: { price: 12, unit: 'W/M', note: 'Minimum charge 1 CBM' },
    exTelex: { price: 35, unit: 'Bill of Lading' },
    exHandling: { price: 30, unit: 'Bill of Lading' },
    exAms: { price: 40, unit: 'Bill of Lading' },
    exEbs: { price: null, unit: 'W/M', note: 'At cost, minimum charge 1 CBM' },
    exLoadUnload: { price: 5, unit: 'W/M' },
    exStorage: { price: 2, unit: 'W/M', note: 'From ... day (Free ... day)' },
    exAmend: { price: 45, unit: 'Bill of Lading' },
    exSwitch: { price: 45, unit: 'Bill of Lading' },
    exLateSi: { price: 45, unit: 'Bill of Lading' },
    exAmsAmend: { price: 50, unit: 'Bill of Lading' },
    exVgm: { price: 10, unit: 'Bill of Lading' },
    imThc: { price: 11, unit: 'W/M', note: 'Minimum charge 1 CBM' },
    imDoFee: { price: 45, unit: 'Bill of Lading' },
    imCfs: { price: 30, unit: 'W/M', note: 'Minimum charge 1 CBM' },
    imHandling: { price: 30, unit: 'Bill of Lading' },
    imCic: { price: 7, unit: 'W/M', note: 'Minimum charge 1 CBM, at cost as per co-loaders' },
    imLowSulfur: { price: 5, unit: 'W/M', note: 'Minimum charge 1 CBM, at cost as per co-loaders' },
  },
  air: {
    hawb: { price: 15, unit: 'Bill of Lading' },
    ams: { price: 25, unit: 'Bill of Lading' },
    airthc: { price: 0.1, unit: 'C.W', note: 'Min 35 USD/shipment' },
    xray: { price: 0.02, unit: 'G.W' },
    dofee: { price: 30, unit: 'Bill of Lading' },
    hdlcharge: { price: 25, unit: 'Bill of Lading' },
    docamend: { price: 45, unit: 'Bill of Lading', note: 'Each amendment request' },
  },
};

export function suggestedFor(mode, key) {
  return TARIFF_SUGGEST[mode]?.[key] || null;
}
